version: "3"

services:
  tu-aplicacion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: printerai_streamlit
    ports:
      - "8501:8501"
    environment:
      - FLOWISE_BASE_URL=https://reinaldoviedo94-flowise.hf.space/
      - FLOWISE_CHATFLOW_ID=5dfad3d2-1f92-4d7d-8196-661c811ad23a
      - FLOWISE_USERNAME=c42ed0ed18dc07cad699a742a4a7cc7c
      - FLOWISE_PASSWORD=ad1602569190bef23d448b7c2453239d

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"